spring:
  application:
    name: Product-Service
  profiles:
#    active: dev
#    active: qa
    active: prod


server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html  #http://localhost:8081/swagger-ui/index.html
  api-docs:
    path: /api-docs #http://localhost:8081/api-docs